[build]
  command = "CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_YARN = "false" 