[build]
  command = "npm install copy-descriptor object-copy --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_FLAGS = "--legacy-peer-deps --force" 